apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kvmorchestrator-validation
webhooks:
  - name: kvmorchestrator.validation.conf
    namespaceSelector:
      matchExpressions:
      - key: control-plane
        operator: DoesNotExist
    clientConfig:
      service:
        name: kvm-orchs-svc
        namespace: kvm-ns
        path: "/keyvaults/orchestrator/validate/"
        port: 443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtRENDQW9BQ0NRRHpFcURFS3JJekJqQU5CZ2txaGtpRzl3MEJBUXNGQURDQmpURUxNQWtHQTFVRUJoTUMKU1U0eEN6QUpCZ05WQkFnTUFrdE9NUXd3Q2dZRFZRUUhEQU5DVGtjeEREQUtCZ05WQkFvTUEwRlFTVEVVTUJJRwpBMVVFQ3d3TFJHVjJaV3h2Y0cxbGJuUXhGekFWQmdOVkJBTU1EbXQyYlM1aGNHa3VjMlZ5ZG1WeU1TWXdKQVlKCktvWklodmNOQVFrQkZoZGtZWFIwWVM1dGIyNXZhbWwwUUdkdFlXbHNMbU52YlRBZUZ3MHlNVEExTWpBeE16QXkKTURSYUZ3MHlNekE0TWpNeE16QXlNRFJhTUlHTk1Rc3dDUVlEVlFRR0V3SkpUakVMTUFrR0ExVUVDQXdDUzA0eApEREFLQmdOVkJBY01BMEpPUnpFTU1Bb0dBMVVFQ2d3RFFWQkpNUlF3RWdZRFZRUUxEQXRFWlhabGJHOXdiV1Z1CmRERVhNQlVHQTFVRUF3d09hM1p0TG1Gd2FTNXpaWEoyWlhJeEpqQWtCZ2txaGtpRzl3MEJDUUVXRjJSaGRIUmgKTG0xdmJtOXFhWFJBWjIxaGFXd3VZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBMm5pUXVHYWxhUEZIYVFUOFhwOVRKMTJQZ3hpS3crNEU5UVVBWEdFekRrWGFKakZLbFlCSzMrWFRBZE9ZCnhkQWZSeElTWTc0UFV2T0NCUFp6bHh2dTRldUtNeHJaTWxMZG5PT1E1V1k5VWtzejZyL3V4Z2VlQUpJcmF0VUoKcDMzUGwrcXBkNDdNMXdSUGhPV0FISEdaNFR6VjVkNmQrZjJrdXI0WDcvQkMrNTZqMmJGQ0hqMEJMRzI5NGRjSApNZm9ST1FXVUtQTXlTV044S0l4dENIUEZwempiZ0NZdDNsWDQ1MklYd2ZVcjZKVFptcUh6SkdpcWRUYnZTT2VZCmlKcmxVenp2TUVGanVVMUFFQjBpQ0RpMTRhVDB2U0t0ajZPTngxNis4d0ZneTBOZTF5Vmx6OWdNc3NsejBMOUQKaEQ4Rk5vWko5MGN6eUIrdEgweldad3lEVFFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFNbTIxTApqQTBZWWhDKzc5a3RGMUhiZzFZQXhqRFJUbjJ6M1grSTN5Q3NibUNtUE9Vam91UHJ2VXVldk9qd0xqS0oyQ1pDCm8zRnVHdzNYekN5WVFHaGJmYTM1OHhYMElPblgyYjJzcFd4NmVTM2IxN2ZvTXFVTFlCbk5TV0RvU1FxQVE5TEkKaGozT1UwTm9Dbi84dENKUGZTVUFSN2d3aHVWdE9qNHdNTUFPWkV0OVBDUGcvdmZuQ3Vhd1hSQjJCc1I0b2dNTgpGV1p0MzU0ci83bWlHYVIrQWI0UXlvYkVSNjhRcGpTSkNuYTVHRDU5LzUwOFErZTR1WGhhbC9MYWtEOUZxZjlrCjUxa1ZDUkZrZHlOZVNEMmNQWFg0MmxlUVMrVndsUDlZOGlGV3QzMDNvVnh5aUFwSlI4Z3lxYXdJTXBlVExsUXcKQlFXb2tEMmNCU0VvZWRPcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["kvm.api.server"]
        apiVersions: ["v1"]
        resources: ["kvmorchestrators"]
    failurePolicy: Fail
    matchPolicy: Equivalent
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5