apiVersion: v1
kind: Service
metadata:
  name: kvm-orchs-svc
  namespace: kvm-ns
  labels:
    app: kvm-orchs
spec:
  ports:
  - port: 80
    name: http
    targetPort: 7081
  - port: 443
    name: https
    targetPort: 7443
  selector:
    app: kvm-orchs-pod 